# Generated by Django 5.0.3 on 2024-06-11 06:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SingerModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='歌手姓名')),
                ('gender', models.CharField(choices=[('0', '女'), ('1', '男')], max_length=5, verbose_name='性别')),
                ('dob', models.DateField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='Song/singers/Img')),
                ('bio', models.TextField(blank=True, default='暂无简介', null=True)),
            ],
            options={
                'db_table': 'singer_model',
            },
        ),
        migrations.CreateModel(
            name='SongModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('song_name', models.CharField(max_length=100, unique=True, verbose_name='歌曲名称')),
                ('song_genre', models.CharField(max_length=100, verbose_name='歌曲风格')),
                ('song_file', models.FileField(upload_to='Song/songs/Files', verbose_name='歌曲文件')),
                ('song_image', models.FileField(upload_to='Song/songs/Imgs', verbose_name='歌曲图片')),
                ('song_lyrics', models.FileField(upload_to='Song/songs/Lyrics', verbose_name='歌词文件')),
                ('song_bio', models.TextField(verbose_name='歌曲简介')),
                ('song_singer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='songs', to='Song.singermodel', verbose_name='歌手')),
            ],
            options={
                'db_table': 'song_model',
            },
        ),
        migrations.CreateModel(
            name='UserSongListModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('list_name', models.CharField(max_length=100, verbose_name='歌曲列表名称')),
                ('song', models.ManyToManyField(related_name='belong_list', to='Song.songmodel')),
            ],
            options={
                'db_table': 'user_song_list',
            },
        ),
    ]
