# Generated by Django 5.0.3 on 2024-06-11 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='姓名')),
                ('email_or_phone', models.CharField(max_length=100, verbose_name='联系方式(邮箱或电话)')),
                ('message', models.TextField(verbose_name='留言')),
            ],
        ),
    ]
